### ISSUE TITLE
I like the idea but I have 2 issues

### ISSUE THREAD

**Issue by divid-design** [EnigmaWeb/email-text-customizer-for-woocommerce#1]
Hi, I like the idea but I have 2 issues:

- the emails are sent twice
- the woocommerce email templates from /assets/emails/ are copied every time I click on any links in wordpress admin, maybe because action hook is fired when 'init'? line 32 in email-text-customizer-for-woocommerce.php
I have tested it only on localhost

**Comment by maevelander** [comment]
Thanks for reporting this. Will look into it ASAP
